import { z } from 'zod';

export const CategoryCodeSchema = z.enum([
  'top_stories',
  'world',
  'business',
  'technology',
  'science',
  'health',
  'sports',
  'entertainment',
  'india',
]);
export type CategoryCode = z.infer<typeof CategoryCodeSchema>;

export const CategorySchema = z.object({
  slug: z.string().min(1),
  name: z.string().min(1),
  code: CategoryCodeSchema,
  description: z.string().default(''),
  icon: z.string().optional(),
  sortOrder: z.number().int().default(0),
  storyCount: z.number().int().nonnegative().default(0),
  isPinned: z.boolean().default(false),
});
export type Category = z.infer<typeof CategorySchema>;

export const CANONICAL_CATEGORIES: Category[] = [
  {
    slug: 'top-stories',
    code: 'top_stories',
    name: 'Top Stories',
    description: 'Latest developing stories and essential global dispatches.',
    icon: 'Star',
    sortOrder: 1,
    storyCount: 0,
    isPinned: true,
  },
  {
    slug: 'technology',
    code: 'technology',
    name: 'Technology',
    description: 'Artificial intelligence, semiconductors, hardware and digital policy.',
    icon: 'Cpu',
    sortOrder: 2,
    storyCount: 0,
    isPinned: true,
  },
  {
    slug: 'business',
    code: 'business',
    name: 'Business',
    description: 'Financial markets, global trade, macroeconomics and enterprise earnings.',
    icon: 'TrendingUp',
    sortOrder: 3,
    storyCount: 0,
    isPinned: true,
  },
  {
    slug: 'world',
    code: 'world',
    name: 'World',
    description: 'International diplomacy, geopolitics, multilateral treaties and governance.',
    icon: 'Globe',
    sortOrder: 4,
    storyCount: 0,
    isPinned: true,
  },
  {
    slug: 'science',
    code: 'science',
    name: 'Science',
    description: 'Space exploration, quantum computing, renewable energy and biotechnology.',
    icon: 'Atom',
    sortOrder: 5,
    storyCount: 0,
    isPinned: false,
  },
  {
    slug: 'health',
    code: 'health',
    name: 'Health',
    description: 'Global epidemiology, medical breakthroughs, clinical trials and public wellness.',
    icon: 'HeartPulse',
    sortOrder: 6,
    storyCount: 0,
    isPinned: false,
  },
  {
    slug: 'sports',
    code: 'sports',
    name: 'Sports',
    description: 'International tournaments, championships, analytics and athletics dispatches.',
    icon: 'Trophy',
    sortOrder: 7,
    storyCount: 0,
    isPinned: false,
  },
  {
    slug: 'entertainment',
    code: 'entertainment',
    name: 'Entertainment',
    description: 'Cinema, streaming media, arts, culture and creative industries.',
    icon: 'Film',
    sortOrder: 8,
    storyCount: 0,
    isPinned: false,
  },
  {
    slug: 'india',
    code: 'india',
    name: 'India',
    description: 'Policy, digital public infrastructure, economy and science in India.',
    icon: 'Compass',
    sortOrder: 9,
    storyCount: 0,
    isPinned: false,
  },
];
