import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    gap: 16,
  },
  emptyContainer: {
    paddingVertical: 32,
    alignItems: 'center',
  },
  emptyText: {
    color: '#64748b',
    fontSize: 14,
    fontStyle: 'italic',
  },
  headingWrapper: {
    marginVertical: 4,
  },
  h1: {
    fontSize: 26,
    fontWeight: '900',
    color: '#f8fafc',
    letterSpacing: -0.5,
    lineHeight: 32,
  },
  h2: {
    fontSize: 20,
    fontWeight: '800',
    color: '#f8fafc',
    letterSpacing: -0.3,
    lineHeight: 26,
  },
  h3: {
    fontSize: 17,
    fontWeight: '700',
    color: '#e2e8f0',
    lineHeight: 22,
  },
  h4: {
    fontSize: 15,
    fontWeight: '600',
    color: '#cbd5e1',
    lineHeight: 20,
  },
  subtext: {
    fontSize: 13,
    color: '#94a3b8',
    marginTop: 4,
  },
  paragraph: {
    fontSize: 15,
    lineHeight: 24,
    color: '#cbd5e1',
    fontWeight: '400',
  },
  summaryCard: {
    backgroundColor: 'rgba(30, 27, 75, 0.4)',
    borderColor: 'rgba(99, 102, 241, 0.3)',
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    gap: 8,
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  pulseDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#818cf8',
  },
  summaryBadge: {
    fontSize: 10,
    fontWeight: '800',
    color: '#818cf8',
    letterSpacing: 1,
  },
  summaryHeadline: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  bulletDot: {
    color: '#818cf8',
    fontSize: 14,
    fontWeight: '700',
  },
  bulletText: {
    fontSize: 13,
    color: '#cbd5e1',
    flex: 1,
    lineHeight: 18,
  },
  quoteCard: {
    borderLeftWidth: 4,
    borderLeftColor: '#3b82f6',
    paddingLeft: 14,
    paddingVertical: 4,
    marginVertical: 6,
  },
  quoteText: {
    fontSize: 16,
    fontStyle: 'italic',
    color: '#e2e8f0',
    lineHeight: 22,
  },
  quoteAttribution: {
    fontSize: 12,
    fontWeight: '700',
    color: '#60a5fa',
    marginTop: 6,
  },
  mediaCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    borderColor: '#1e293b',
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    gap: 8,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardTypeBadge: {
    fontSize: 10,
    fontWeight: '800',
    color: '#3b82f6',
    letterSpacing: 0.8,
  },
  cardMetaText: {
    fontSize: 11,
    color: '#64748b',
    fontFamily: 'monospace',
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#f8fafc',
  },
  cardSubtitle: {
    fontSize: 12,
    color: '#94a3b8',
  },
  chartValuesContainer: {
    marginTop: 8,
    gap: 6,
  },
  chartValueRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  chartValueLabel: {
    fontSize: 12,
    color: '#94a3b8',
  },
  chartValueNumber: {
    fontSize: 13,
    fontWeight: '700',
    color: '#f8fafc',
    fontFamily: 'monospace',
  },
  sourceFootnote: {
    fontSize: 10,
    color: '#64748b',
    fontStyle: 'italic',
    marginTop: 4,
  },
  timelineList: {
    marginTop: 8,
    gap: 12,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  timelineStepBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    borderWidth: 1,
    borderColor: '#3b82f6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineStepText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#3b82f6',
  },
  timelineContent: {
    flex: 1,
  },
  timelineDate: {
    fontSize: 10,
    fontWeight: '700',
    color: '#60a5fa',
    textTransform: 'uppercase',
  },
  timelineHeadline: {
    fontSize: 13,
    fontWeight: '700',
    color: '#f8fafc',
    marginTop: 1,
  },
  timelineBody: {
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 2,
    lineHeight: 15,
  },
  markerContainer: {
    marginTop: 6,
    gap: 4,
  },
  markerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  markerPin: {
    fontSize: 12,
  },
  markerTitle: {
    fontSize: 12,
    color: '#e2e8f0',
    fontWeight: '600',
  },
  statCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    borderColor: '#1e293b',
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    gap: 4,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  statValue: {
    fontSize: 32,
    fontWeight: '900',
    color: '#f8fafc',
    letterSpacing: -0.5,
  },
  trendPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  trendUp: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
  },
  trendDown: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
  },
  trendText: {
    fontSize: 12,
    fontWeight: '800',
  },
  trendTextUp: {
    color: '#34d399',
  },
  trendTextDown: {
    color: '#f87171',
  },
  statContext: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 2,
  },
  calloutCard: {
    backgroundColor: 'rgba(30, 41, 59, 0.5)',
    borderColor: '#334155',
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    gap: 4,
  },
  calloutTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#f8fafc',
  },
  calloutText: {
    fontSize: 13,
    color: '#cbd5e1',
    lineHeight: 18,
  },
  videoPlaceholder: {
    height: 140,
    backgroundColor: '#020617',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginVertical: 4,
  },
  videoIcon: {
    fontSize: 28,
    color: '#60a5fa',
  },
  videoUrlText: {
    fontSize: 10,
    color: '#64748b',
    paddingHorizontal: 16,
    fontFamily: 'monospace',
  },
  captionText: {
    fontSize: 11,
    color: '#94a3b8',
  },
  audioCard: {
    backgroundColor: 'rgba(30, 27, 75, 0.3)',
    borderColor: '#4338ca',
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    gap: 6,
  },
  narratorText: {
    fontSize: 11,
    color: '#a5b4fc',
  },
  transcriptSnippet: {
    fontSize: 12,
    color: '#cbd5e1',
    fontStyle: 'italic',
    marginTop: 4,
  },
  sourceCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    borderColor: '#1e293b',
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    gap: 4,
  },
  sourcePublisher: {
    fontSize: 10,
    fontWeight: '800',
    color: '#818cf8',
    textTransform: 'uppercase',
  },
  sourceDate: {
    fontSize: 10,
    color: '#64748b',
    fontFamily: 'monospace',
  },
  sourceTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#f8fafc',
  },
  entityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    borderColor: '#1e293b',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    gap: 10,
  },
  entityAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(99, 102, 241, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  entityAvatarText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#818cf8',
  },
  entityInfo: {
    flex: 1,
  },
  entityName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#f8fafc',
  },
  entityTypeBadge: {
    fontSize: 9,
    fontWeight: '800',
    color: '#818cf8',
    textTransform: 'uppercase',
  },
  entityDescription: {
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 2,
  },
  diffCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    borderColor: '#1e293b',
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    gap: 6,
  },
  diffHeader: {
    fontSize: 12,
    fontWeight: '700',
    color: '#f8fafc',
  },
  diffItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  diffBadge: {
    fontSize: 9,
    fontWeight: '800',
    color: '#34d399',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
  },
  diffText: {
    fontSize: 11,
    color: '#cbd5e1',
    flex: 1,
  },
  tableScroll: {
    marginTop: 4,
  },
  table: {
    borderWidth: 1,
    borderColor: '#334155',
    borderRadius: 8,
    overflow: 'hidden',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#1e293b',
  },
  tableHeaderCell: {
    padding: 8,
    fontSize: 11,
    fontWeight: '700',
    color: '#f8fafc',
    minWidth: 90,
  },
  tableRow: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#334155',
  },
  tableCell: {
    padding: 8,
    fontSize: 11,
    color: '#cbd5e1',
    minWidth: 90,
  },
});
