import type { Publisher, Source } from '@ai-news/schemas';

export const baselinePublishers: Publisher[] = [
  {
    id: 'pub_the_hindu',
    organizationId: 'org_default',
    name: 'The Hindu',
    slug: 'the-hindu',
    domain: 'thehindu.com',
    logoUrl:
      'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=160&auto=format&fit=crop&q=80',
    description:
      "One of India's most respected English-language daily newspapers, founded in 1878.",
    category: 'general',
    country: 'India',
    language: 'en',
    websiteUrl: 'https://www.thehindu.com',
    biasRating: 'Center / Independent',
    credibilityScore: 96,
    isVerified: true,
    followerCount: 1840,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'pub_reuters',
    organizationId: 'org_default',
    name: 'Reuters',
    slug: 'reuters',
    domain: 'reuters.com',
    logoUrl:
      'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=160&auto=format&fit=crop&q=80',
    description:
      'Global news agency and financial markets intelligence provider with worldwide editorial bureaus.',
    category: 'general',
    country: 'United Kingdom',
    language: 'en',
    websiteUrl: 'https://www.reuters.com',
    biasRating: 'Center',
    credibilityScore: 98,
    isVerified: true,
    followerCount: 5200,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'pub_techcrunch',
    organizationId: 'org_default',
    name: 'TechCrunch',
    slug: 'techcrunch',
    domain: 'techcrunch.com',
    logoUrl:
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=160&auto=format&fit=crop&q=80',
    description:
      'Premier technology and venture publication covering AI breakthroughs, hardware foundries, and startup innovation.',
    category: 'technology',
    country: 'United States',
    language: 'en',
    websiteUrl: 'https://techcrunch.com',
    biasRating: 'Tech Analytical',
    credibilityScore: 92,
    isVerified: true,
    followerCount: 2600,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'pub_bloomberg',
    organizationId: 'org_default',
    name: 'Bloomberg Markets',
    slug: 'bloomberg',
    domain: 'bloomberg.com',
    logoUrl:
      'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=160&auto=format&fit=crop&q=80',
    description:
      'Comprehensive international market data, bond yield curves, macro analyses, and central bank coverage.',
    category: 'business',
    country: 'United States',
    language: 'en',
    websiteUrl: 'https://www.bloomberg.com',
    biasRating: 'Center-Right Analytical',
    credibilityScore: 97,
    isVerified: true,
    followerCount: 4100,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'pub_nature',
    organizationId: 'org_default',
    name: 'Nature Scientific Journal',
    slug: 'nature',
    domain: 'nature.com',
    logoUrl:
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=160&auto=format&fit=crop&q=80',
    description:
      'Preeminent peer-reviewed scientific journal publishing landmark discoveries in physics, biology, and materials science.',
    category: 'science',
    country: 'United Kingdom',
    language: 'en',
    websiteUrl: 'https://www.nature.com',
    biasRating: 'Scientific Nonpartisan',
    credibilityScore: 99,
    isVerified: true,
    followerCount: 3800,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'pub_mit_tech_review',
    organizationId: 'org_default',
    name: 'MIT Technology Review',
    slug: 'mit-tech-review',
    domain: 'technologyreview.com',
    logoUrl:
      'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=160&auto=format&fit=crop&q=80',
    description:
      'Authoritative authority on the commercial, ethical, and societal impacts of emerging engineering systems.',
    category: 'technology',
    country: 'United States',
    language: 'en',
    websiteUrl: 'https://www.technologyreview.com',
    biasRating: 'Analytical Independent',
    credibilityScore: 98,
    isVerified: true,
    followerCount: 3100,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'pub_financial_times',
    organizationId: 'org_default',
    name: 'Financial Times',
    slug: 'financial-times',
    domain: 'ft.com',
    logoUrl:
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=160&auto=format&fit=crop&q=80',
    description:
      'International business daily providing rigorous coverage of foreign exchange, central bank policy, and diplomatic trade.',
    category: 'business',
    country: 'United Kingdom',
    language: 'en',
    websiteUrl: 'https://www.ft.com',
    biasRating: 'Center Independent',
    credibilityScore: 97,
    isVerified: true,
    followerCount: 4400,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'pub_ap_news',
    organizationId: 'org_default',
    name: 'Associated Press',
    slug: 'ap-news',
    domain: 'apnews.com',
    logoUrl:
      'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=160&auto=format&fit=crop&q=80',
    description:
      'Independent global news cooperative dedicated to factual, nonpartisan journalism across 100 countries.',
    category: 'general',
    country: 'United States',
    language: 'en',
    websiteUrl: 'https://apnews.com',
    biasRating: 'Strictly Nonpartisan Wire',
    credibilityScore: 99,
    isVerified: true,
    followerCount: 6500,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
];

export const baselineSources: Source[] = [
  {
    id: 'src_hindu_01',
    organizationId: 'org_default',
    publisherId: 'pub_the_hindu',
    domain: 'thehindu.com',
    url: 'https://thehindu.com/news/national/india-multilateral-trade-accord-2026',
    canonicalUrl: 'https://thehindu.com/news/national/india-multilateral-trade-accord-2026',
    title: 'India Seals Multilateral Trade Settlement Framework at New Delhi Summit',
    publisher: 'The Hindu',
    author: 'Special Diplomatic Correspondent',
    publishedAt: '2026-09-26T09:00:00Z',
    retrievedAt: '2026-09-26T09:15:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'Negotiators in New Delhi agreed to the landmark accession protocols establishing direct local-currency exchange mechanisms.',
    createdAt: '2026-09-26T09:00:00Z',
    updatedAt: '2026-09-26T09:00:00Z',
  },
  {
    id: 'src_hindu_02',
    organizationId: 'org_default',
    publisherId: 'pub_the_hindu',
    domain: 'thehindu.com',
    url: 'https://thehindu.com/business/economy/cross-border-currency-clearing',
    canonicalUrl: 'https://thehindu.com/business/economy/cross-border-currency-clearing',
    title: 'Reserve Bank Unveils Sovereign Clearing Channels for Asian Bilateral Trade',
    publisher: 'The Hindu',
    author: 'Banking & Macroeconomics Desk',
    publishedAt: '2026-09-26T11:45:00Z',
    retrievedAt: '2026-09-26T12:00:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'The central bank issued operational directives permitting bilateral clearing accounts without third-party intermediary currencies.',
    createdAt: '2026-09-26T11:45:00Z',
    updatedAt: '2026-09-26T11:45:00Z',
  },
  {
    id: 'src_reuters_01',
    organizationId: 'org_default',
    publisherId: 'pub_reuters',
    domain: 'reuters.com',
    url: 'https://reuters.example.com/world/brics-summit-accord-2026',
    canonicalUrl: 'https://reuters.example.com/world/brics-summit-accord-2026',
    title: 'BRICS Leaders Reach Comprehensive Accession Accord',
    publisher: 'Reuters Global Wire',
    author: 'Diplomatic Affairs Bureau',
    publishedAt: '2026-09-26T08:00:00Z',
    retrievedAt: '2026-09-26T08:15:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'The member states formally adopt the New Delhi multilateral settlement framework.',
    createdAt: '2026-09-26T08:00:00Z',
    updatedAt: '2026-09-26T08:00:00Z',
  },
  {
    id: 'src_mea_gov',
    organizationId: 'org_default',
    domain: 'mea.gov.in',
    url: 'https://mea.gov.in/brics-declaration-2026.htm',
    canonicalUrl: 'https://mea.gov.in/brics-declaration-2026.htm',
    title: 'Official Treaty: 2026 New Delhi Declaration',
    publisher: 'Ministry of External Affairs',
    author: 'Summit Secretariat',
    publishedAt: '2026-09-26T09:30:00Z',
    retrievedAt: '2026-09-26T09:45:00Z',
    language: 'en',
    sourceType: 'OFFICIAL_DOCUMENT',
    permissibleExcerpt:
      'Article 4: Cross-border clearing among member states shall be denominated in local currencies.',
    createdAt: '2026-09-26T09:30:00Z',
    updatedAt: '2026-09-26T09:30:00Z',
  },
  {
    id: 'src_techcrunch_01',
    organizationId: 'org_default',
    publisherId: 'pub_techcrunch',
    domain: 'techcrunch.com',
    url: 'https://techcrunch.com/2026/09/27/semiconductor-consortium-2nm-patent-pool',
    canonicalUrl: 'https://techcrunch.com/2026/09/27/semiconductor-consortium-2nm-patent-pool',
    title: 'Global Chipmakers Form Unified 2nm Patent Alliance',
    publisher: 'TechCrunch',
    author: 'Silicon & Hardware Desk',
    publishedAt: '2026-09-27T11:00:00Z',
    retrievedAt: '2026-09-27T11:15:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'The consortium aligns High-NA EUV optical tolerances and chiplet packaging standards under a shared patent pool.',
    createdAt: '2026-09-27T11:00:00Z',
    updatedAt: '2026-09-27T11:00:00Z',
  },
  {
    id: 'src_bloomberg_01',
    organizationId: 'org_default',
    publisherId: 'pub_bloomberg',
    domain: 'bloomberg.com',
    url: 'https://bloomberg.com/news/articles/2026-09-29/central-banks-activate-liquidity-facility',
    canonicalUrl:
      'https://bloomberg.com/news/articles/2026-09-29/central-banks-activate-liquidity-facility',
    title: 'Central Banks Inaugurate Bilateral FX Clearing Grid',
    publisher: 'Bloomberg Markets',
    author: 'Global Financial Wire',
    publishedAt: '2026-09-29T13:30:00Z',
    retrievedAt: '2026-09-29T13:45:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'The multilateral liquidity architecture mitigates settlement risk across currency pairs through automated collateral pledging.',
    createdAt: '2026-09-29T13:30:00Z',
    updatedAt: '2026-09-29T13:30:00Z',
  },
  {
    id: 'src_nature_01',
    organizationId: 'org_default',
    publisherId: 'pub_nature',
    domain: 'nature.com',
    url: 'https://www.nature.com/articles/s41586-026-09823-1',
    canonicalUrl: 'https://www.nature.com/articles/s41586-026-09823-1',
    title: 'Steady-State Fusion Burning Plasma in High-Field Superconducting Tokamaks',
    publisher: 'Nature',
    author: 'Dr. Helen Thorne et al.',
    publishedAt: '2026-09-28T06:00:00Z',
    retrievedAt: '2026-09-28T07:00:00Z',
    language: 'en',
    sourceType: 'ACADEMIC_PAPER',
    permissibleExcerpt:
      'We report continuous plasma confinement exceeding 120 seconds with energy multiplication factor Q = 1.35.',
    createdAt: '2026-09-28T06:00:00Z',
    updatedAt: '2026-09-28T06:00:00Z',
  },
  {
    id: 'src_mit_tech_01',
    organizationId: 'org_default',
    publisherId: 'pub_mit_tech_review',
    domain: 'technologyreview.com',
    url: 'https://technologyreview.com/2026/09/30/verifiable-agent-verification-protocols',
    canonicalUrl: 'https://technologyreview.com/2026/09/30/verifiable-agent-verification-protocols',
    title: 'Formal Verification Loops Enable Safe Deployment of Autonomous Software Agents',
    publisher: 'MIT Technology Review',
    author: 'Kavita Subramanian',
    publishedAt: '2026-09-30T08:00:00Z',
    retrievedAt: '2026-09-30T08:30:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'Multi-agent formal verification loops eliminated 99.98% of synthesized logic regressions before live promotion.',
    createdAt: '2026-09-30T08:00:00Z',
    updatedAt: '2026-09-30T08:00:00Z',
  },
  {
    id: 'src_ft_01',
    organizationId: 'org_default',
    publisherId: 'pub_financial_times',
    domain: 'ft.com',
    url: 'https://ft.com/content/sovereign-liquidity-grid-clearing-analysis-2026',
    canonicalUrl: 'https://ft.com/content/sovereign-liquidity-grid-clearing-analysis-2026',
    title: 'Global Reserve Realignment: The Rise of Multilateral Currency Clearing',
    publisher: 'Financial Times',
    author: 'Gillian Tett & Martin Wolf',
    publishedAt: '2026-09-29T15:00:00Z',
    retrievedAt: '2026-09-29T15:30:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'Central banks are prioritizing bilateral swap facilities as reserve diversification accelerates.',
    createdAt: '2026-09-29T15:00:00Z',
    updatedAt: '2026-09-29T15:00:00Z',
  },
  {
    id: 'src_esa_01',
    organizationId: 'org_default',
    domain: 'esa.int',
    url: 'https://esa.int/science/artemis-lunar-gateway-halo-insertion',
    canonicalUrl: 'https://esa.int/science/artemis-lunar-gateway-halo-insertion',
    title: 'International Lunar Gateway Insertion Telemetry Vector Finalized',
    publisher: 'European Space Agency',
    author: 'Mission Control Directorate',
    publishedAt: '2026-09-29T18:00:00Z',
    retrievedAt: '2026-09-29T18:30:00Z',
    language: 'en',
    sourceType: 'OFFICIAL_DOCUMENT',
    permissibleExcerpt:
      'The near-rectilinear halo orbit insertion burn completed at 18:22 UTC with nominal propellant margins.',
    createdAt: '2026-09-29T18:00:00Z',
    updatedAt: '2026-09-29T18:00:00Z',
  },
  {
    id: 'src_cern_01',
    organizationId: 'org_default',
    domain: 'cern.ch',
    url: 'https://cern.ch/press/releases/2026/quantum-entanglement-density',
    canonicalUrl: 'https://cern.ch/press/releases/2026/quantum-entanglement-density',
    title: 'CERN Confirms Record Quantum Correlation in High-Luminosity Collider Collisions',
    publisher: 'CERN Directorate',
    author: 'CMS Collaboration',
    publishedAt: '2026-09-28T14:00:00Z',
    retrievedAt: '2026-09-28T14:30:00Z',
    language: 'en',
    sourceType: 'PRESS_RELEASE',
    permissibleExcerpt:
      'Multiparticle quantum entanglement was measured at TeV scales, setting an empirical milestone for quantum field theory.',
    createdAt: '2026-09-28T14:00:00Z',
    updatedAt: '2026-09-28T14:00:00Z',
  },
  {
    id: 'src_who_01',
    organizationId: 'org_default',
    domain: 'who.int',
    url: 'https://who.int/publications/2026/pan-coronavirus-vaccine-phase3',
    canonicalUrl: 'https://who.int/publications/2026/pan-coronavirus-vaccine-phase3',
    title: 'Consensus Evaluation: Broad-Spectrum Synthetic Antigen Phase 3 Global Trial',
    publisher: 'World Health Organization',
    author: 'Strategic Advisory Group of Experts',
    publishedAt: '2026-09-27T10:00:00Z',
    retrievedAt: '2026-09-27T10:30:00Z',
    language: 'en',
    sourceType: 'OFFICIAL_DOCUMENT',
    permissibleExcerpt:
      'The targeted mRNA construct neutralized all circulating sublineages with a 94.2% efficacy profile.',
    createdAt: '2026-09-27T10:00:00Z',
    updatedAt: '2026-09-27T10:00:00Z',
  },
  {
    id: 'src_ap_01',
    organizationId: 'org_default',
    publisherId: 'pub_ap_news',
    domain: 'apnews.com',
    url: 'https://apnews.com/article/venice-film-festival-generative-ai-cinema-2026',
    canonicalUrl: 'https://apnews.com/article/venice-film-festival-generative-ai-cinema-2026',
    title: 'Venice Film Festival Unveils First Juried Synthetic Feature Film Showcase',
    publisher: 'Associated Press',
    author: 'Arts & Cultural Bureau',
    publishedAt: '2026-09-30T16:00:00Z',
    retrievedAt: '2026-09-30T16:20:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'Directors demonstrated real-time generative lighting, acoustic synthesis, and neural rendering in competition films.',
    createdAt: '2026-09-30T16:00:00Z',
    updatedAt: '2026-09-30T16:00:00Z',
  },
  {
    id: 'src_us_cert_01',
    organizationId: 'org_default',
    domain: 'cisa.gov',
    url: 'https://cisa.gov/news-events/cybersecurity-advisories/aa26-274a',
    canonicalUrl: 'https://cisa.gov/news-events/cybersecurity-advisories/aa26-274a',
    title: 'Mitigating Route Integrity Exploits Across Critical Infrastructure Networks',
    publisher: 'Cybersecurity and Infrastructure Security Agency',
    author: 'Joint Cyber Defense Collaborative',
    publishedAt: '2026-09-28T20:00:00Z',
    retrievedAt: '2026-09-28T20:15:00Z',
    language: 'en',
    sourceType: 'OFFICIAL_DOCUMENT',
    permissibleExcerpt:
      'Operational technology operators must enforce cryptographic route origin authorizations to prevent telemetry hijacking.',
    createdAt: '2026-09-28T20:00:00Z',
    updatedAt: '2026-09-28T20:00:00Z',
  },
];
