import type { Topic, Entity, Category } from '@ai-news/schemas';
import { CANONICAL_CATEGORIES } from '@ai-news/schemas';

export const baselineCategories: Category[] = CANONICAL_CATEGORIES.map((c) => ({
  ...c,
  id: c.id || `cat_${c.code || c.slug.replace(/-/g, '_')}`,
}));

export const baselineTopics: Topic[] = [
  {
    id: 'top_geopolitics',
    organizationId: 'org_default',
    slug: 'geopolitics',
    name: 'Global Geopolitics',
    description:
      'International treaties, multilateral summits, diplomatic accords, and sovereign governance.',
    aliases: ['diplomacy', 'foreign-policy', 'summits', 'treaties'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_brics_2026',
    organizationId: 'org_default',
    slug: 'brics-2026',
    name: 'BRICS Summit 2026',
    parentTopicId: 'top_geopolitics',
    description:
      'Coverage of the 2026 New Delhi multilateral summit, accession protocols, and clearing architecture.',
    aliases: ['brics', 'brics-summit', 'new-delhi-accord', 'multilateral-trade'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_semiconductors',
    organizationId: 'org_default',
    slug: 'semiconductors',
    name: 'Semiconductors & Fabrication',
    description:
      'Advanced High-NA EUV lithography, 2nm gate-all-around foundry nodes, and chip packaging.',
    aliases: ['chips', 'lithography', 'euv', 'foundries', 'gate-all-around'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_energy_fusion',
    organizationId: 'org_default',
    slug: 'fusion-energy',
    name: 'Nuclear Fusion Energy',
    description:
      'Commercial net-energy gain milestones, high-temperature superconducting tokamaks, and plasma burning.',
    aliases: ['fusion', 'tokamak', 'plasma-physics', 'net-gain'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_ai_agents',
    organizationId: 'org_default',
    slug: 'autonomous-ai-agents',
    name: 'Autonomous AI Agents',
    description:
      'Multi-agent verification workflows, benchmark evaluations, code generation, and production telemetry.',
    aliases: ['agents', 'autonomous-systems', 'llm-agents', 'mcp-clients'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_macroeconomics',
    organizationId: 'org_default',
    slug: 'macroeconomics',
    name: 'Global Macroeconomics',
    description:
      'Central bank liquidity facilities, sovereign currency clearing, interest rate benchmarks, and FX corridors.',
    aliases: ['monetary-policy', 'central-banks', 'liquidity', 'currencies', 'forex'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_quantum_computing',
    organizationId: 'org_default',
    slug: 'quantum-computing',
    name: 'Quantum Computing & Cryptography',
    description:
      'Topological qubits, fault-tolerant quantum error correction, and post-quantum cryptographic standards.',
    aliases: ['quantum', 'qubits', 'pqc', 'quantum-supremacy'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_climate_transition',
    organizationId: 'org_default',
    slug: 'climate-transition',
    name: 'Clean Energy & Grid Transition',
    description:
      'Solid-state battery deployments, long-duration grid storage, HVDC interconnects, and decarbonization.',
    aliases: ['renewables', 'grid-storage', 'batteries', 'cleantech'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_space_exploration',
    organizationId: 'org_default',
    slug: 'space-exploration',
    name: 'Space Exploration & Orbital Infrastructure',
    description:
      'Lunar Gateway missions, Starship orbital cadence, satellite mega-constellations, and deep-space science.',
    aliases: ['space', 'starship', 'artemis', 'lunar-gateway', 'orbital'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_cybersecurity',
    organizationId: 'org_default',
    slug: 'cybersecurity',
    name: 'Cybersecurity & Infrastructure Defense',
    description:
      'Critical telemetry protection, zero-day mitigation, BGP routing defense, and cryptographic key governance.',
    aliases: ['infosec', 'zero-day', 'cisa', 'grid-security'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_biotech_crispr',
    organizationId: 'org_default',
    slug: 'biotech-and-genomics',
    name: 'Biotech & Synthetic Genomics',
    description:
      'Pan-pathogen mRNA therapeutics, targeted CRISPR gene editing, and synthetic protein design.',
    aliases: ['genomics', 'crispr', 'mrna', 'biomedicine'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_sovereign_wealth',
    organizationId: 'org_default',
    slug: 'sovereign-wealth',
    name: 'Sovereign Wealth & Capital Flows',
    description:
      'Global state-backed investment vehicles, infrastructure funds, and bilateral capital treaties.',
    aliases: ['swf', 'capital-flows', 'sovereign-investments'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_robotics',
    organizationId: 'org_default',
    slug: 'humanoid-robotics',
    name: 'Humanoid Robotics & Automation',
    description:
      'Next-generation embodied AI, bipedal humanoid manipulators, and automated assembly ecosystems.',
    aliases: ['robotics', 'humanoids', 'embodied-ai', 'automation'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_digital_currency',
    organizationId: 'org_default',
    slug: 'digital-currencies',
    name: 'Digital Currencies & Clearing',
    description:
      'Wholesale central bank digital currencies, tokenized sovereign bonds, and programmable settlement.',
    aliases: ['cbdc', 'programmable-money', 'digital-clearing'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_media_provenance',
    organizationId: 'org_default',
    slug: 'media-provenance',
    name: 'Information Provenance & Verification',
    description:
      'C2PA metadata standards, cryptographic content watermarks, fact-checking, and deepfake verification.',
    aliases: ['provenance', 'c2pa', 'verification', 'deepfakes'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'top_culture_cinema',
    organizationId: 'org_default',
    slug: 'culture-and-cinema',
    name: 'Culture & Synthetic Media',
    description:
      'Generative filmmaking, Venice Biennale showcases, digital performance arts, and creative intellectual property.',
    aliases: ['cinema', 'culture', 'filmmaking', 'generative-arts'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
];

export const baselineEntities: Entity[] = [
  {
    id: 'ent_india',
    organizationId: 'org_default',
    slug: 'india',
    name: 'Republic of India',
    type: 'COUNTRY',
    aliases: ['Bharat', 'IN'],
    description:
      'Host nation of the 2026 multilateral economic summit and pioneer in unified instant payments.',
    metadata: { capital: 'New Delhi', region: 'South Asia' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_tsmc',
    organizationId: 'org_default',
    slug: 'tsmc',
    name: 'Taiwan Semiconductor Manufacturing Co.',
    type: 'ORGANIZATION',
    aliases: ['TSMC', 'Taiwan Semi'],
    description:
      'World leading semiconductor foundry and pioneer of 2nm gate-all-around nodes and advanced chiplet packaging.',
    metadata: { ticker: 'TSM', industry: 'Semiconductors' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_usa',
    organizationId: 'org_default',
    slug: 'united-states',
    name: 'United States of America',
    type: 'COUNTRY',
    aliases: ['USA', 'US'],
    description:
      'Major federal jurisdiction leading AI research, deep-space exploration, and advanced capital markets.',
    metadata: { capital: 'Washington, D.C.', region: 'North America' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_eu',
    organizationId: 'org_default',
    slug: 'european-union',
    name: 'European Union',
    type: 'INSTITUTION',
    aliases: ['EU', 'European Commission'],
    description:
      'Supranational confederation standardizing international digital services, privacy frameworks, and clean energy directives.',
    metadata: { headquarters: 'Brussels, Belgium' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_nvidia',
    organizationId: 'org_default',
    slug: 'nvidia',
    name: 'NVIDIA Corporation',
    type: 'ORGANIZATION',
    aliases: ['NVDA', 'Nvidia'],
    description:
      'Dominant designer of GPU accelerated computing architectures and AI datacenter interconnects.',
    metadata: { ticker: 'NVDA', industry: 'Accelerated Computing' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_deepmind',
    organizationId: 'org_default',
    slug: 'google-deepmind',
    name: 'Google DeepMind',
    type: 'ORGANIZATION',
    aliases: ['DeepMind', 'Gemini Team'],
    description:
      'Pioneering artificial intelligence research lab responsible for AlphaFold, Gemini, and frontier reasoning models.',
    metadata: { parent: 'Alphabet Inc.' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_openai',
    organizationId: 'org_default',
    slug: 'openai',
    name: 'OpenAI',
    type: 'ORGANIZATION',
    aliases: ['OpenAI Inc.'],
    description:
      'Frontier AI research and deployment enterprise developing multimodal reasoning models and operator agents.',
    metadata: { headquarters: 'San Francisco, CA' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_isro',
    organizationId: 'org_default',
    slug: 'isro',
    name: 'Indian Space Research Organisation',
    type: 'ORGANIZATION',
    aliases: ['ISRO'],
    description:
      'National space agency of India, renowned for cost-efficient lunar and interplanetary exploration.',
    metadata: { headquarters: 'Bengaluru, India' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_cern',
    organizationId: 'org_default',
    slug: 'cern',
    name: 'European Organization for Nuclear Research (CERN)',
    type: 'ORGANIZATION',
    aliases: ['CERN', 'LHC'],
    description:
      'Global particle physics laboratory operating the Large Hadron Collider in Geneva.',
    metadata: { location: 'Geneva, Switzerland' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_who',
    organizationId: 'org_default',
    slug: 'who',
    name: 'World Health Organization',
    type: 'ORGANIZATION',
    aliases: ['WHO'],
    description:
      'United Nations specialized agency coordinating international public health responses and pathogen surveillance.',
    metadata: { headquarters: 'Geneva, Switzerland' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_jensen_huang',
    organizationId: 'org_default',
    slug: 'jensen-huang',
    name: 'Jensen Huang',
    type: 'PERSON',
    aliases: ['Jen-Hsun Huang'],
    description:
      'Founder and Chief Executive Officer of NVIDIA Corporation, architect of GPU computing.',
    metadata: { role: 'CEO', company: 'NVIDIA' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_demis_hassabis',
    organizationId: 'org_default',
    slug: 'demis-hassabis',
    name: 'Demis Hassabis',
    type: 'PERSON',
    aliases: ['Sir Demis Hassabis'],
    description:
      'Nobel laureate, neuroscientist, and CEO of Google DeepMind, leading frontier AI science.',
    metadata: { role: 'CEO', company: 'Google DeepMind' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_sam_altman',
    organizationId: 'org_default',
    slug: 'sam-altman',
    name: 'Sam Altman',
    type: 'PERSON',
    aliases: ['Samuel H. Altman'],
    description:
      'Chief Executive Officer of OpenAI, advocate for global compute infrastructure investment.',
    metadata: { role: 'CEO', company: 'OpenAI' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ent_iter',
    organizationId: 'org_default',
    slug: 'iter-tokamak',
    name: 'ITER Tokamak Reactor',
    type: 'TECHNOLOGY',
    aliases: ['ITER', 'International Thermonuclear Experimental Reactor'],
    description:
      'World largest magnetic confinement plasma physics experiment located in Saint-Paul-lez-Durance, France.',
    metadata: { location: 'Cadarache, France' },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
];
