import type { Story, Source } from '@ai-news/schemas';

export const DEMO_SOURCES: Record<string, Source> = {
  src_reuters: {
    id: 'src_reuters',
    organizationId: 'org_default',
    url: 'https://reuters.example.com/world/brics-summit-2026-trade-accord',
    canonicalUrl: 'https://reuters.example.com/world/brics-summit-2026-trade-accord',
    title: 'BRICS Leaders Reach Historic Bilateral Trade Settlement Framework',
    publisher: 'Reuters',
    author: 'Diplomatic Bureau',
    publishedAt: '2026-09-26T10:15:00Z',
    retrievedAt: '2026-09-26T10:30:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt: 'Delegates representing the expanded 10-nation bloc ratified terms for sovereign local-currency settlement.',
    createdAt: '2026-09-26T10:30:00Z',
    updatedAt: '2026-09-26T10:30:00Z',
  },
  src_bloomberg: {
    id: 'src_bloomberg',
    organizationId: 'org_default',
    url: 'https://bloomberg.example.com/markets/brics-currency-volume',
    title: 'Trade Volume Across Emerging Markets Surges to $2.1 Trillion',
    publisher: 'Bloomberg',
    author: 'Financial Intelligence',
    publishedAt: '2026-09-26T08:00:00Z',
    retrievedAt: '2026-09-26T08:30:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt: 'Non-dollar settlement accounts for over 38% of total commerce within member states.',
    createdAt: '2026-09-26T08:30:00Z',
    updatedAt: '2026-09-26T08:30:00Z',
  },
  src_official: {
    id: 'src_official',
    organizationId: 'org_default',
    url: 'https://secretariat.brics2026.gov/declaration-final',
    title: 'New Delhi Declaration: Leaders Joint Communiqué on Sustainable Growth and AI Cooperation',
    publisher: 'BRICS Summit Secretariat',
    publishedAt: '2026-09-26T14:00:00Z',
    retrievedAt: '2026-09-26T14:15:00Z',
    language: 'en',
    sourceType: 'OFFICIAL_DOCUMENT',
    permissibleExcerpt: 'We resolve to establish an open technological exchange framework ensuring equitable access to advanced compute and energy resources.',
    createdAt: '2026-09-26T14:15:00Z',
    updatedAt: '2026-09-26T14:15:00Z',
  },
};

export const DEMO_STORIES: Story[] = [
  {
    id: 'sty_brics_2026',
    organizationId: 'org_default',
    slug: 'brics-2026-summit-ratifies-landmark-trade-pact',
    title: 'BRICS 2026 Summit Ratifies Landmark Trade Accord in New Delhi',
    summary: 'Delegates representing the expanded 10-nation bloc finalize terms for sovereign local-currency settlements and launch joint AI compute standards.',
    status: 'PUBLISHED',
    articleType: 'developing_story',
    currentVersionNumber: 3,
    currentVersionId: 'ver_brics_v3',
    topicIds: ['top_brics_2026', 'top_global_trade', 'top_ai_policy'],
    entityIds: ['ent_india', 'ent_china', 'ent_brazil', 'ent_russia', 'ent_south_africa'],
    sourceIds: ['src_reuters', 'src_bloomberg', 'src_official'],
    heroImageUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1600&q=80',
    createdVia: 'mcp',
    createdByClient: 'gemini_spark',
    authorId: 'usr_gemini_spark_agent',
    publishedAt: '2026-09-26T14:45:00Z',
    createdAt: '2026-09-26T09:00:00Z',
    updatedAt: '2026-09-26T14:45:00Z',
    blocks: [
      {
        id: 'wc_brics',
        blockType: 'what_changed',
        sortOrder: 0,
        data: {
          previousVersionNumber: 2,
          updatedAt: '2026-09-26T14:45:00Z',
          items: [
            {
              changeType: 'added',
              description: 'Incorporated official Joint Communiqué terms on shared compute clusters.',
              affectedSection: 'paragraph',
            },
            {
              changeType: 'updated',
              description: 'Updated Intra-Bloc Settlement chart with verified 2026 Q3 data from Central Bank registry.',
              affectedSection: 'chart',
            },
            {
              changeType: 'corrected',
              description: 'Corrected ratification count: 10 member states unanimously confirmed, not 9.',
            },
          ],
        },
      },
      {
        id: 'sum_brics',
        blockType: 'summary',
        sortOrder: 1,
        data: {
          headline: 'Key Summit Decisions & Economic Impact',
          bulletPoints: [
            'Full rollout of bilateral currency clearing accounts without third-party intermediary currencies.',
            'Creation of a $50B multilateral clean technology and microelectronics transition facility.',
            'Adoption of the New Delhi AI Governance Framework emphasizing open-weights scientific models.',
          ],
        },
      },
      {
        id: 'p_lead',
        blockType: 'paragraph',
        sortOrder: 2,
        data: {
          text: 'NEW DELHI — In a decisive conclusion to the 18th annual diplomatic summit, heads of state ratified the Comprehensive Economic Integration Protocol, creating an automated bilateral settlement network designed to facilitate commerce across 3.6 billion citizens.',
          format: 'markdown',
        },
      },
      {
        id: 'chart_volume',
        blockType: 'chart',
        sortOrder: 3,
        data: {
          chartType: 'bar',
          title: 'Intra-Bloc Settlement Volume (2022-2026)',
          subtitle: 'Trillion USD equivalent cleared in sovereign currencies',
          xAxis: { key: 'year', label: 'Fiscal Year', type: 'category' },
          yAxis: { label: 'Trillion USD', format: '$' },
          series: [{ name: 'Settlement Volume', key: 'vol', color: '#3b82f6' }],
          values: [
            { year: '2022', vol: 0.42 },
            { year: '2023', vol: 0.68 },
            { year: '2024', vol: 1.15 },
            { year: '2025', vol: 1.62 },
            { year: '2026', vol: 2.14 },
          ],
          sourceAttribution: 'Bloomberg Intelligence / Multilateral Secretariat Registry',
        },
      },
      {
        id: 'map_venues',
        blockType: 'map',
        sortOrder: 4,
        data: {
          title: 'Summit Venue & Member State Representation',
          center: [77.209, 28.6139],
          zoom: 4,
          style: 'dark',
          markers: [
            { coordinates: [77.209, 28.6139], title: 'Summit Plenary Hall (New Delhi)' },
            { coordinates: [72.8777, 19.076], title: 'Financial Coordination Bureau (Mumbai)' },
          ],
        },
      },
      {
        id: 'quote_leader',
        blockType: 'quote',
        sortOrder: 5,
        data: {
          quote: 'Our goal is not isolation, but resilience. By building resilient financial infrastructure and pooling computational research, we establish an engine for shared prosperity.',
          attribution: 'Summit Conference Chair',
          title: 'Plenary Closing Remarks',
        },
      },
      {
        id: 'tl_summit',
        blockType: 'timeline',
        sortOrder: 6,
        data: {
          title: 'Summit Milestone Chronology',
          items: [
            { date: 'Day 1 • 09:00', headline: 'Opening Session', body: 'Delegations arrive and confirm the final agenda.' },
            { date: 'Day 2 • 14:00', headline: 'Financial Ministers Accord', body: 'Technical working groups harmonize clearing protocol.' },
            { date: 'Day 3 • 16:30', headline: 'Unanimous Adoption', body: 'Final joint declaration ratified and released to international press.' },
          ],
        },
      },
      {
        id: 'cit_official',
        blockType: 'citation',
        sortOrder: 7,
        data: {
          claim: 'Intra-bloc settlement volume reached $2.14 Trillion in 2026',
          sourceIds: ['src_bloomberg', 'src_reuters'],
        },
      },
    ],
  },
  {
    id: 'sty_semi_01',
    organizationId: 'org_default',
    slug: 'global-semiconductor-consortium-formed',
    title: 'Global Semiconductor Consortium Establishes 2nm Lithography Standard',
    summary: 'Leading fabrication foundries and research universities establish an open patent pool for advanced packaging and gate-all-around architectures.',
    status: 'PUBLISHED',
    articleType: 'technology',
    currentVersionNumber: 2,
    currentVersionId: 'ver_semi_v2',
    topicIds: ['top_semiconductors', 'top_ai_hardware'],
    entityIds: ['ent_tsmc', 'ent_intel', 'ent_samsung'],
    sourceIds: ['src_reuters'],
    heroImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=80',
    createdVia: 'mcp',
    createdByClient: 'chatgpt',
    authorId: 'usr_chatgpt_agent',
    publishedAt: '2026-09-26T12:00:00Z',
    createdAt: '2026-09-26T08:00:00Z',
    updatedAt: '2026-09-26T12:00:00Z',
    blocks: [
      {
        id: 'sum_semi',
        blockType: 'summary',
        sortOrder: 0,
        data: {
          headline: 'Consortium Highlights',
          bulletPoints: [
            'Unification of High-NA EUV optical tolerances across major equipment vendors.',
            'Open-standard chiplet interconnect framework targeting under 0.8pJ/bit power dissipation.',
          ],
        },
      },
      {
        id: 'p_semi',
        blockType: 'paragraph',
        sortOrder: 1,
        data: {
          text: 'TAIPEI — In a strategic shift toward interoperable fabrication, a coalition of top semiconductor foundries and research institutes announced a shared framework for 2-nanometer process nodes, aiming to reduce multi-billion-dollar R&D redundancies.',
          format: 'markdown',
        },
      },
      {
        id: 'chart_fab',
        blockType: 'chart',
        sortOrder: 2,
        data: {
          chartType: 'line',
          title: 'Projected 2nm Wafer Capacity (2025-2028)',
          xAxis: { key: 'year', label: 'Year', type: 'category' },
          yAxis: { label: 'Wafers / Month (K)', format: '' },
          series: [
            { name: 'Consortium Members', key: 'consortium', color: '#10b981' },
            { name: 'Independent Foundries', key: 'independent', color: '#94a3b8' },
          ],
          values: [
            { year: '2025', consortium: 15, independent: 8 },
            { year: '2026', consortium: 45, independent: 18 },
            { year: '2027', consortium: 110, independent: 35 },
            { year: '2028', consortium: 230, independent: 60 },
          ],
        },
      },
    ],
  },
  {
    id: 'sty_fusion_01',
    organizationId: 'org_default',
    slug: 'fusion-reactor-test-reaches-net-energy-gain',
    title: 'Magnetic Fusion Reactor Sustains Net Energy Gain for 120 Seconds',
    summary: 'High-temperature superconducting magnets maintain steady-state fusion plasma at an unprecedented 1.35x Q-factor.',
    status: 'PUBLISHED',
    articleType: 'science',
    currentVersionNumber: 1,
    currentVersionId: 'ver_fusion_v1',
    topicIds: ['top_clean_energy', 'top_physics'],
    entityIds: ['ent_iter', 'ent_mit'],
    sourceIds: ['src_reuters'],
    heroImageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=1600&q=80',
    createdVia: 'mcp',
    createdByClient: 'gemini',
    authorId: 'usr_gemini_agent',
    publishedAt: '2026-09-26T07:30:00Z',
    createdAt: '2026-09-26T07:30:00Z',
    updatedAt: '2026-09-26T07:30:00Z',
    blocks: [
      {
        id: 'kpi_fusion',
        blockType: 'chart',
        sortOrder: 0,
        data: {
          chartType: 'kpi',
          title: 'Peak Plasma Q-Factor (Energy Gain Ratio)',
          xAxis: { type: 'category', key: 'round', label: 'Test Round' },
          yAxis: { label: 'Ratio' },
          series: [{ name: 'Q-Factor', key: 'q' }],
          values: [{ round: 'Test 1', q: 1.05 }, { round: 'Test 2', q: 1.35 }],
        },
      },
      {
        id: 'p_fusion',
        blockType: 'paragraph',
        sortOrder: 1,
        data: {
          text: 'OXFORD — Experimental physicists achieved a major milestone toward grid-scale nuclear fusion, maintaining a plasma burning phase for two full minutes with a net positive energy return.',
          format: 'markdown',
        },
      },
    ],
  },
];
