import type { Story, Source, Entity, Event, Publisher, FactCheckClaim } from '@ai-news/schemas';

export const DEMO_PUBLISHERS: Record<string, Publisher> = {
  pub_the_hindu: {
    id: 'pub_the_hindu',
    organizationId: 'org_default',
    name: 'The Hindu',
    slug: 'the-hindu',
    domain: 'thehindu.com',
    logoUrl:
      'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=160&auto=format&fit=crop&q=80',
    description:
      "One of India's most respected English-language daily newspapers, founded in 1878, renowned for investigative integrity and independent analysis.",
    category: 'general',
    country: 'India',
    language: 'en',
    websiteUrl: 'https://www.thehindu.com',
    biasRating: 'Center / Independent',
    credibilityScore: 96,
    isVerified: true,
    followerCount: 1840,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-26T10:00:00Z',
  },
  pub_reuters: {
    id: 'pub_reuters',
    organizationId: 'org_default',
    name: 'Reuters',
    slug: 'reuters',
    domain: 'reuters.com',
    logoUrl:
      'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=160&auto=format&fit=crop&q=80',
    description:
      'International news organization providing breaking global wire dispatches, financial intelligence, and factual reporting.',
    category: 'world',
    country: 'Global',
    language: 'en',
    websiteUrl: 'https://www.reuters.com',
    biasRating: 'Wire / Factual',
    credibilityScore: 98,
    isVerified: true,
    followerCount: 4210,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-26T10:00:00Z',
  },
  pub_bloomberg: {
    id: 'pub_bloomberg',
    organizationId: 'org_default',
    name: 'Bloomberg',
    slug: 'bloomberg',
    domain: 'bloomberg.com',
    logoUrl:
      'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=160&auto=format&fit=crop&q=80',
    description:
      'Premier business, financial markets, and economic data agency tracking commodities, macroeconomic shifts, and capital flows.',
    category: 'business',
    country: 'United States',
    language: 'en',
    websiteUrl: 'https://www.bloomberg.com',
    biasRating: 'Market Focused',
    credibilityScore: 95,
    isVerified: true,
    followerCount: 3950,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-26T10:00:00Z',
  },
  pub_techcrunch: {
    id: 'pub_techcrunch',
    organizationId: 'org_default',
    name: 'TechCrunch',
    slug: 'techcrunch',
    domain: 'techcrunch.com',
    logoUrl:
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=160&auto=format&fit=crop&q=80',
    description:
      'Silicon Valley and international tech publication covering artificial intelligence breakthroughs, semiconductors, and startup ventures.',
    category: 'technology',
    country: 'United States',
    language: 'en',
    websiteUrl: 'https://techcrunch.com',
    biasRating: 'Center / Tech Analytical',
    credibilityScore: 92,
    isVerified: true,
    followerCount: 2600,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-26T10:00:00Z',
  },
  pub_nature: {
    id: 'pub_nature',
    organizationId: 'org_default',
    name: 'Nature',
    slug: 'nature',
    domain: 'nature.com',
    logoUrl:
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=160&auto=format&fit=crop&q=80',
    description:
      'Peer-reviewed multidisciplinary scientific journal publishing groundbreaking research across physics, biotechnology, and quantum theory.',
    category: 'science',
    country: 'United Kingdom',
    language: 'en',
    websiteUrl: 'https://www.nature.com',
    biasRating: 'Peer-Reviewed Science',
    credibilityScore: 99,
    isVerified: true,
    followerCount: 1540,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-26T10:00:00Z',
  },
  pub_ap: {
    id: 'pub_ap',
    organizationId: 'org_default',
    name: 'Associated Press',
    slug: 'apnews',
    domain: 'apnews.com',
    logoUrl:
      'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=160&auto=format&fit=crop&q=80',
    description:
      'Global not-for-profit news agency committed to unbiased journalism, real-time wire reporting, and fact verification.',
    category: 'world',
    country: 'Global',
    language: 'en',
    websiteUrl: 'https://apnews.com',
    biasRating: 'Unbiased Wire',
    credibilityScore: 98,
    isVerified: true,
    followerCount: 3100,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-26T10:00:00Z',
  },
};

export const DEMO_SOURCES: Record<string, Source> = {
  src_hindu_news1: {
    id: 'src_hindu_news1',
    organizationId: 'org_default',
    publisherId: 'pub_the_hindu',
    domain: 'thehindu.com',
    url: 'https://thehindu.com/news/national/india-multilateral-trade-accord-2026',
    canonicalUrl: 'https://thehindu.com/news/national/india-multilateral-trade-accord-2026',
    title: 'India Seals Multilateral Trade Settlement Framework at New Delhi Summit',
    publisher: 'The Hindu',
    author: 'Special Diplomatic Correspondent',
    publishedAt: '2026-09-26T09:00:00Z',
    retrievedAt: '2026-09-26T09:15:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'Negotiators in New Delhi agreed to the landmark accession protocols establishing direct local-currency exchange mechanisms.',
    createdAt: '2026-09-26T09:15:00Z',
    updatedAt: '2026-09-26T09:15:00Z',
  },
  src_hindu_news2: {
    id: 'src_hindu_news2',
    organizationId: 'org_default',
    publisherId: 'pub_the_hindu',
    domain: 'thehindu.com',
    url: 'https://thehindu.com/business/economy/cross-border-currency-clearing',
    canonicalUrl: 'https://thehindu.com/business/economy/cross-border-currency-clearing',
    title: 'Reserve Bank Unveils Sovereign Clearing Channels for Asian Bilateral Trade',
    publisher: 'The Hindu',
    author: 'Banking & Macroeconomics Desk',
    publishedAt: '2026-09-26T11:45:00Z',
    retrievedAt: '2026-09-26T12:00:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'The central bank issued operational directives permitting bilateral clearing accounts without third-party intermediary currencies.',
    createdAt: '2026-09-26T12:00:00Z',
    updatedAt: '2026-09-26T12:00:00Z',
  },
  src_reuters: {
    id: 'src_reuters',
    organizationId: 'org_default',
    publisherId: 'pub_reuters',
    domain: 'reuters.com',
    url: 'https://reuters.example.com/world/brics-summit-2026-trade-accord',
    canonicalUrl: 'https://reuters.example.com/world/brics-summit-2026-trade-accord',
    title: 'BRICS Leaders Reach Historic Bilateral Trade Settlement Framework',
    publisher: 'Reuters',
    author: 'Diplomatic Bureau',
    publishedAt: '2026-09-26T10:15:00Z',
    retrievedAt: '2026-09-26T10:30:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'Delegates representing the expanded 10-nation bloc ratified terms for sovereign local-currency settlement.',
    createdAt: '2026-09-26T10:30:00Z',
    updatedAt: '2026-09-26T10:30:00Z',
  },
  src_bloomberg: {
    id: 'src_bloomberg',
    organizationId: 'org_default',
    publisherId: 'pub_bloomberg',
    domain: 'bloomberg.com',
    url: 'https://bloomberg.example.com/markets/brics-currency-volume',
    title: 'Trade Volume Across Emerging Markets Surges to $2.1 Trillion',
    publisher: 'Bloomberg',
    author: 'Financial Intelligence',
    publishedAt: '2026-09-26T08:00:00Z',
    retrievedAt: '2026-09-26T08:30:00Z',
    language: 'en',
    sourceType: 'NEWS_ARTICLE',
    permissibleExcerpt:
      'Non-dollar settlement accounts for over 38% of total commerce within member states.',
    createdAt: '2026-09-26T08:30:00Z',
    updatedAt: '2026-09-26T08:30:00Z',
  },
  src_official: {
    id: 'src_official',
    organizationId: 'org_default',
    publisherId: 'pub_ap',
    domain: 'brics2026.gov',
    url: 'https://secretariat.brics2026.gov/declaration-final',
    title:
      'New Delhi Declaration: Leaders Joint Communiqué on Sustainable Growth and AI Cooperation',
    publisher: 'BRICS Summit Secretariat',
    publishedAt: '2026-09-26T14:00:00Z',
    retrievedAt: '2026-09-26T14:15:00Z',
    language: 'en',
    sourceType: 'OFFICIAL_DOCUMENT',
    permissibleExcerpt:
      'We resolve to establish an open technological exchange framework ensuring equitable access to advanced compute and energy resources.',
    createdAt: '2026-09-26T14:15:00Z',
    updatedAt: '2026-09-26T14:15:00Z',
  },
};

export const DEMO_STORIES: Story[] = [
  {
    id: 'sty_brics_2026',
    organizationId: 'org_default',
    slug: 'brics-2026-summit-ratifies-landmark-trade-pact',
    title: 'BRICS 2026 Summit Ratifies Landmark Trade Accord in New Delhi',
    summary:
      'Delegates representing the expanded 10-nation bloc finalize terms for sovereign local-currency settlements and launch joint AI compute standards.',
    status: 'PUBLISHED',
    articleType: 'developing_story',
    currentVersionNumber: 3,
    currentVersionId: 'ver_brics_v3',
    topicIds: ['top_brics_2026', 'top_global_trade', 'top_ai_policy'],
    entityIds: ['ent_india', 'ent_china', 'ent_brazil', 'ent_russia', 'ent_south_africa'],
    sourceIds: ['src_reuters', 'src_bloomberg', 'src_official'],
    heroImageUrl:
      'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1600&q=80',
    createdVia: 'mcp',
    createdByClient: 'gemini_spark',
    authorId: 'usr_gemini_spark_agent',
    publishedAt: '2026-09-26T14:45:00Z',
    createdAt: '2026-09-26T09:00:00Z',
    updatedAt: '2026-09-26T14:45:00Z',
    blocks: [
      {
        id: 'wc_brics',
        blockType: 'what_changed',
        sortOrder: 0,
        data: {
          previousVersionNumber: 2,
          updatedAt: '2026-09-26T14:45:00Z',
          items: [
            {
              changeType: 'added',
              description:
                'Incorporated official Joint Communiqué terms on shared compute clusters.',
              affectedSection: 'paragraph',
            },
            {
              changeType: 'updated',
              description:
                'Updated Intra-Bloc Settlement chart with verified 2026 Q3 data from Central Bank registry.',
              affectedSection: 'chart',
            },
            {
              changeType: 'corrected',
              description:
                'Corrected ratification count: 10 member states unanimously confirmed, not 9.',
            },
          ],
        },
      },
      {
        id: 'sum_brics',
        blockType: 'summary',
        sortOrder: 1,
        data: {
          headline: 'Key Summit Decisions & Economic Impact',
          bulletPoints: [
            'Full rollout of bilateral currency clearing accounts without third-party intermediary currencies.',
            'Creation of a $50B multilateral clean technology and microelectronics transition facility.',
            'Adoption of the New Delhi AI Governance Framework emphasizing open-weights scientific models.',
          ],
        },
      },
      {
        id: 'p_lead',
        blockType: 'paragraph',
        sortOrder: 2,
        data: {
          text: 'NEW DELHI — In a decisive conclusion to the 18th annual diplomatic summit, heads of state ratified the Comprehensive Economic Integration Protocol, creating an automated bilateral settlement network designed to facilitate commerce across 3.6 billion citizens.',
          format: 'markdown',
        },
      },
      {
        id: 'chart_volume',
        blockType: 'chart',
        sortOrder: 3,
        data: {
          chartType: 'bar',
          title: 'Intra-Bloc Settlement Volume (2022-2026)',
          subtitle: 'Trillion USD equivalent cleared in sovereign currencies',
          xAxis: { key: 'year', label: 'Fiscal Year', type: 'category' },
          yAxis: { label: 'Trillion USD', format: '$' },
          series: [{ name: 'Settlement Volume', key: 'vol', color: '#3b82f6' }],
          values: [
            { year: '2022', vol: 0.42 },
            { year: '2023', vol: 0.68 },
            { year: '2024', vol: 1.15 },
            { year: '2025', vol: 1.62 },
            { year: '2026', vol: 2.14 },
          ],
          sourceAttribution: 'Bloomberg Intelligence / Multilateral Secretariat Registry',
        },
      },
      {
        id: 'map_venues',
        blockType: 'map',
        sortOrder: 4,
        data: {
          title: 'Summit Venue & Member State Representation',
          center: [77.209, 28.6139],
          zoom: 4,
          style: 'dark',
          markers: [
            { coordinates: [77.209, 28.6139], title: 'Summit Plenary Hall (New Delhi)' },
            { coordinates: [72.8777, 19.076], title: 'Financial Coordination Bureau (Mumbai)' },
          ],
        },
      },
      {
        id: 'quote_leader',
        blockType: 'quote',
        sortOrder: 5,
        data: {
          quote:
            'Our goal is not isolation, but resilience. By building resilient financial infrastructure and pooling computational research, we establish an engine for shared prosperity.',
          attribution: 'Summit Conference Chair',
          title: 'Plenary Closing Remarks',
        },
      },
      {
        id: 'tl_summit',
        blockType: 'timeline',
        sortOrder: 6,
        data: {
          title: 'Summit Milestone Chronology',
          items: [
            {
              date: 'Day 1 • 09:00',
              headline: 'Opening Session',
              body: 'Delegations arrive and confirm the final agenda.',
            },
            {
              date: 'Day 2 • 14:00',
              headline: 'Financial Ministers Accord',
              body: 'Technical working groups harmonize clearing protocol.',
            },
            {
              date: 'Day 3 • 16:30',
              headline: 'Unanimous Adoption',
              body: 'Final joint declaration ratified and released to international press.',
            },
          ],
        },
      },
      {
        id: 'cit_official',
        blockType: 'citation',
        sortOrder: 7,
        data: {
          claim: 'Intra-bloc settlement volume reached $2.14 Trillion in 2026',
          sourceIds: ['src_bloomberg', 'src_reuters'],
        },
      },
    ],
  },
  {
    id: 'sty_semi_01',
    organizationId: 'org_default',
    slug: 'global-semiconductor-consortium-formed',
    title: 'Global Semiconductor Consortium Establishes 2nm Lithography Standard',
    summary:
      'Leading fabrication foundries and research universities establish an open patent pool for advanced packaging and gate-all-around architectures.',
    status: 'PUBLISHED',
    articleType: 'technology',
    currentVersionNumber: 2,
    currentVersionId: 'ver_semi_v2',
    topicIds: ['top_semiconductors', 'top_ai_hardware'],
    entityIds: ['ent_tsmc', 'ent_intel', 'ent_samsung'],
    sourceIds: ['src_reuters'],
    heroImageUrl:
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=80',
    createdVia: 'mcp',
    createdByClient: 'chatgpt',
    authorId: 'usr_chatgpt_agent',
    publishedAt: '2026-09-26T12:00:00Z',
    createdAt: '2026-09-26T08:00:00Z',
    updatedAt: '2026-09-26T12:00:00Z',
    blocks: [
      {
        id: 'sum_semi',
        blockType: 'summary',
        sortOrder: 0,
        data: {
          headline: 'Consortium Highlights',
          bulletPoints: [
            'Unification of High-NA EUV optical tolerances across major equipment vendors.',
            'Open-standard chiplet interconnect framework targeting under 0.8pJ/bit power dissipation.',
          ],
        },
      },
      {
        id: 'p_semi',
        blockType: 'paragraph',
        sortOrder: 1,
        data: {
          text: 'TAIPEI — In a strategic shift toward interoperable fabrication, a coalition of top semiconductor foundries and research institutes announced a shared framework for 2-nanometer process nodes, aiming to reduce multi-billion-dollar R&D redundancies.',
          format: 'markdown',
        },
      },
      {
        id: 'chart_fab',
        blockType: 'chart',
        sortOrder: 2,
        data: {
          chartType: 'line',
          title: 'Projected 2nm Wafer Capacity (2025-2028)',
          xAxis: { key: 'year', label: 'Year', type: 'category' },
          yAxis: { label: 'Wafers / Month (K)', format: '' },
          series: [
            { name: 'Consortium Members', key: 'consortium', color: '#10b981' },
            { name: 'Independent Foundries', key: 'independent', color: '#94a3b8' },
          ],
          values: [
            { year: '2025', consortium: 15, independent: 8 },
            { year: '2026', consortium: 45, independent: 18 },
            { year: '2027', consortium: 110, independent: 35 },
            { year: '2028', consortium: 230, independent: 60 },
          ],
        },
      },
    ],
  },
  {
    id: 'sty_fusion_01',
    organizationId: 'org_default',
    slug: 'fusion-reactor-test-reaches-net-energy-gain',
    title: 'Magnetic Fusion Reactor Sustains Net Energy Gain for 120 Seconds',
    summary:
      'High-temperature superconducting magnets maintain steady-state fusion plasma at an unprecedented 1.35x Q-factor.',
    status: 'PUBLISHED',
    articleType: 'science',
    currentVersionNumber: 1,
    currentVersionId: 'ver_fusion_v1',
    topicIds: ['top_clean_energy', 'top_physics'],
    entityIds: ['ent_iter', 'ent_mit'],
    sourceIds: ['src_reuters'],
    heroImageUrl:
      'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=1600&q=80',
    createdVia: 'mcp',
    createdByClient: 'gemini',
    authorId: 'usr_gemini_agent',
    publishedAt: '2026-09-26T07:30:00Z',
    createdAt: '2026-09-26T07:30:00Z',
    updatedAt: '2026-09-26T07:30:00Z',
    blocks: [
      {
        id: 'kpi_fusion',
        blockType: 'chart',
        sortOrder: 0,
        data: {
          chartType: 'kpi',
          title: 'Peak Plasma Q-Factor (Energy Gain Ratio)',
          xAxis: { type: 'category', key: 'round', label: 'Test Round' },
          yAxis: { label: 'Ratio' },
          series: [{ name: 'Q-Factor', key: 'q' }],
          values: [
            { round: 'Test 1', q: 1.05 },
            { round: 'Test 2', q: 1.35 },
          ],
        },
      },
      {
        id: 'p_fusion',
        blockType: 'paragraph',
        sortOrder: 1,
        data: {
          text: 'OXFORD — Experimental physicists achieved a major milestone toward grid-scale nuclear fusion, maintaining a plasma burning phase for two full minutes with a net positive energy return.',
          format: 'markdown',
        },
      },
    ],
  },
];

export const DEMO_ENTITIES: Record<string, Entity> = {
  ent_india: {
    id: 'ent_india',
    organizationId: 'org_default',
    name: 'Republic of India',
    slug: 'india',
    type: 'COUNTRY',
    description:
      'Host nation of the 2026 BRICS summit in New Delhi and architect of the bilateral trade settlement framework.',
    aliases: ['India', 'Bharat', 'New Delhi Administration'],
    createdAt: '2026-09-26T00:00:00Z',
    updatedAt: '2026-09-26T00:00:00Z',
  },
  ent_china: {
    id: 'ent_china',
    organizationId: 'org_default',
    name: "People's Republic of China",
    slug: 'china',
    type: 'COUNTRY',
    description:
      'Key participant in the bilateral trade settlement protocol and co-sponsor of the open scientific compute framework.',
    aliases: ['China', 'Beijing'],
    createdAt: '2026-09-26T00:00:00Z',
    updatedAt: '2026-09-26T00:00:00Z',
  },
  ent_brazil: {
    id: 'ent_brazil',
    organizationId: 'org_default',
    name: 'Federative Republic of Brazil',
    slug: 'brazil',
    type: 'COUNTRY',
    description:
      'South American founding member supporting sovereign currency clearing and agricultural trade agreements.',
    aliases: ['Brazil', 'Brasília'],
    createdAt: '2026-09-26T00:00:00Z',
    updatedAt: '2026-09-26T00:00:00Z',
  },
  ent_tsmc: {
    id: 'ent_tsmc',
    organizationId: 'org_default',
    name: 'Taiwan Semiconductor Manufacturing Co.',
    slug: 'tsmc',
    type: 'ORGANIZATION',
    description:
      'World-leading dedicated semiconductor foundry co-founding the 2nm High-NA EUV lithography consortium.',
    aliases: ['TSMC', 'Taiwan Semiconductor'],
    createdAt: '2026-09-26T00:00:00Z',
    updatedAt: '2026-09-26T00:00:00Z',
  },
  ent_intel: {
    id: 'ent_intel',
    organizationId: 'org_default',
    name: 'Intel Corporation',
    slug: 'intel',
    type: 'ORGANIZATION',
    description:
      'Global microchip manufacturer contributing advanced packaging and open chiplet interconnect specifications.',
    aliases: ['Intel', 'Intel Foundry'],
    createdAt: '2026-09-26T00:00:00Z',
    updatedAt: '2026-09-26T00:00:00Z',
  },
  ent_samsung: {
    id: 'ent_samsung',
    organizationId: 'org_default',
    name: 'Samsung Electronics',
    slug: 'samsung',
    type: 'ORGANIZATION',
    description:
      'Multinational electronics and memory leader standardizing Gate-All-Around (GAA) transistor architectures.',
    aliases: ['Samsung', 'Samsung Foundry'],
    createdAt: '2026-09-26T00:00:00Z',
    updatedAt: '2026-09-26T00:00:00Z',
  },
  ent_iter: {
    id: 'ent_iter',
    organizationId: 'org_default',
    name: 'ITER Organization',
    slug: 'iter',
    type: 'INSTITUTION',
    description:
      'International nuclear fusion research mega-project validating burning plasma physics and magnetic confinement.',
    aliases: ['ITER', 'International Thermonuclear Experimental Reactor'],
    createdAt: '2026-09-26T00:00:00Z',
    updatedAt: '2026-09-26T00:00:00Z',
  },
  ent_mit: {
    id: 'ent_mit',
    organizationId: 'org_default',
    name: 'MIT Plasma Science and Fusion Center',
    slug: 'mit',
    type: 'INSTITUTION',
    description:
      'Academic research laboratory pioneering high-field superconducting magnets for commercial net-energy fusion.',
    aliases: ['MIT PSFC', 'Massachusetts Institute of Technology'],
    createdAt: '2026-09-26T00:00:00Z',
    updatedAt: '2026-09-26T00:00:00Z',
  },
};

export const DEMO_EVENTS: Record<string, Event> = {
  evt_brics_2026: {
    id: 'evt_brics_2026',
    organizationId: 'org_default',
    title: 'BRICS 2026 Leaders Summit in New Delhi',
    summary:
      'Historic multilateral summit uniting 10 nations to establish sovereign bilateral clearing networks and open AI computing exchange.',
    status: 'ACTIVE',
    occurredAt: '2026-09-26T09:00:00Z',
    location: 'Bharat Mandapam, New Delhi, India',
    coordinates: [77.209, 28.6139],
    topicIds: ['top_brics_2026', 'top_global_trade', 'top_ai_policy'],
    entityIds: ['ent_india', 'ent_china', 'ent_brazil'],
    storyIds: ['sty_brics_2026'],
    sourceIds: ['src_reuters', 'src_bloomberg', 'src_official'],
    createdAt: '2026-09-26T09:00:00Z',
    updatedAt: '2026-09-26T14:45:00Z',
  },
  evt_semi_consortium: {
    id: 'evt_semi_consortium',
    organizationId: 'org_default',
    title: 'Formation of 2nm Semiconductor Lithography Consortium',
    summary:
      'Cross-foundry alliance standardizing High-NA EUV tolerances, packaging, and open-source chiplet interconnect topologies.',
    status: 'ACTIVE',
    occurredAt: '2026-09-26T12:00:00Z',
    location: 'Taipei International Convention Center, Taiwan',
    coordinates: [121.5654, 25.033],
    topicIds: ['top_semiconductors', 'top_ai_hardware'],
    entityIds: ['ent_tsmc', 'ent_intel', 'ent_samsung'],
    storyIds: ['sty_semi_01'],
    sourceIds: ['src_reuters'],
    createdAt: '2026-09-26T08:00:00Z',
    updatedAt: '2026-09-26T12:00:00Z',
  },
  evt_fusion_milestone: {
    id: 'evt_fusion_milestone',
    organizationId: 'org_default',
    title: 'Steady-State Burning Plasma Net Gain Verification',
    summary:
      'Magnetic confinement fusion reactor sustains steady-state plasma at 1.35x Q-factor for 120 consecutive seconds.',
    status: 'RESOLVED',
    occurredAt: '2026-09-26T07:30:00Z',
    location: 'Culham Centre for Fusion Energy, Oxfordshire, UK',
    coordinates: [-1.2577, 51.752],
    topicIds: ['top_clean_energy', 'top_physics'],
    entityIds: ['ent_iter', 'ent_mit'],
    storyIds: ['sty_fusion_01'],
    sourceIds: ['src_reuters'],
    createdAt: '2026-09-26T07:30:00Z',
    updatedAt: '2026-09-26T07:30:00Z',
  },
};

export const DEMO_FACT_CHECKS: FactCheckClaim[] = [
  {
    id: 'fc_01',
    claim: 'Solar storms completely dismantled international undersea internet cables.',
    claimant: 'Viral Social Media Posts',
    rating: 'FALSE',
    summary:
      'Undersea fiber optic cables operate via light pulses immune to geomagnetic fluctuations. Only surface equipment experienced minor transient surges.',
    checker: 'GlobalPulse Verification Desk',
    sources: ['NOAA Space Weather Prediction Center', 'International Cable Protection Committee'],
    url: 'https://www.swpc.noaa.gov',
    checkedAt: '2026-10-02T10:00:00Z',
  },
  {
    id: 'fc_02',
    claim: 'Central Banks quietly agreed to eliminate physical cash currencies by 2027.',
    claimant: 'Blog Speculation',
    rating: 'FALSE',
    summary:
      'Central Bank Digital Currencies (CBDCs) are experimental supplements. Official policy frameworks explicitly mandate cash availability.',
    checker: 'Reuters Fact Check',
    sources: ['Bank for International Settlements', 'Federal Reserve Board Policy Release'],
    url: 'https://www.bis.org',
    checkedAt: '2026-10-02T08:30:00Z',
  },
  {
    id: 'fc_03',
    claim: 'CERN set a new quantum entanglement record in particle collision density.',
    claimant: 'Physics Conference Dispatches',
    rating: 'TRUE',
    summary:
      'Peer-reviewed measurements at the Large Hadron Collider confirm unprecedented quantum correlation metrics in top-quark pairs.',
    checker: 'Science Verification Network',
    sources: ['Physical Review Letters', 'CERN Directorate'],
    url: 'https://home.cern',
    checkedAt: '2026-10-01T18:00:00Z',
  },
  {
    id: 'fc_04',
    claim:
      'Leaked benchmark indicates frontier AI model reached autonomous artificial general intelligence.',
    claimant: 'Anonymous Tech Forum Leak',
    rating: 'FALSE',
    summary:
      'The leaked document was an unverified prompt-engineering benchmark with synthetic evaluations and missing validation telemetry.',
    checker: 'Tech & AI Verification Bureau',
    sources: ['Frontier Model Forum', 'Stanford AI Index Consortium'],
    url: 'https://aiindex.stanford.edu',
    checkedAt: '2026-10-01T12:00:00Z',
  },
  {
    id: 'fc_05',
    claim: 'Antarctic winter sea ice extent hit an all-time 45-year satellite record high in 2026.',
    claimant: 'Climate Denialist Podcast',
    rating: 'FALSE',
    summary:
      'Copernicus and NSIDC satellite sensor arrays confirmed sea ice extent was 1.2 million sq km below the 1991-2020 climatological mean.',
    checker: 'Global Climate Science Desk',
    sources: ['Copernicus Climate Change Service', 'National Snow and Ice Data Center (NSIDC)'],
    url: 'https://nsidc.org',
    checkedAt: '2026-09-30T16:00:00Z',
  },
  {
    id: 'fc_06',
    claim:
      'World Health Organization initiated global advisory regarding bioaccumulative microplastics in cardiovascular tissue.',
    claimant: 'Medical Research Digest',
    rating: 'MOSTLY_TRUE',
    summary:
      'WHO published an updated technical advisory urging stricter monitoring of nanoplastics in cardiovascular circulation, but did not declare a binding emergency.',
    checker: 'Health Verification Network',
    sources: ['World Health Organization Bulletin', 'The Lancet Oncology'],
    url: 'https://www.who.int',
    checkedAt: '2026-09-29T14:00:00Z',
  },
  {
    id: 'fc_07',
    claim:
      'Commercial nuclear fusion facility achieved continuous net-positive power supply to national electrical grid.',
    claimant: 'Viral Clean Energy Clip',
    rating: 'MIXTURE',
    summary:
      'The pilot reactor achieved transient Q > 1.25 energy gain in a magnetic containment test pulse, but grid interconnection is scheduled for 2029 pilot trials.',
    checker: 'Energy Intelligence Wire',
    sources: ['International Atomic Energy Agency (IAEA)', 'ITER Organization'],
    url: 'https://www.iaea.org',
    checkedAt: '2026-09-28T11:20:00Z',
  },
  {
    id: 'fc_08',
    claim:
      'International Monetary Fund mandated gold-backed reserves for cross-border bilateral settlements.',
    claimant: 'Finance Telegram Channels',
    rating: 'FALSE',
    summary:
      'The IMF Articles of Agreement explicitly maintain Special Drawing Rights (SDRs) and multi-currency foreign exchange reserves without gold mandate.',
    checker: 'Reuters Fact Check',
    sources: ['International Monetary Fund Media Advisory', 'BIS Quarterly Review'],
    url: 'https://www.imf.org',
    checkedAt: '2026-09-27T09:15:00Z',
  },
];
